trigger:
  branches:
    include:
      - main
  paths:
    include:
      - implementations/vidchain-agbar/vidchain-agbar-backend

pr: none

resources:
- repo: self

variables:
  # Docker Buildkit improves image build performance
  DOCKER_BUILDKIT: 1
  # Image repository
  agbarBackendRepo: 'agbar-backend'
  agbarBackendRepoEndpoint: 'k8scrvidchainpro.azurecr.io/agbar-backend'
  # Dockerfiles
  agbarBackendDocker: 'implementations/vidchain-agbar/vidchain-agbar-backend/Dockerfile'
  # Kubernetes YAML
  agbarBackendKubernetes: 'implementations/vidchain-agbar/vidchain-agbar-backend/k8s/k8s-pro.yml'
  # Configmaps
  agbarBackendConfigMap: 'implementations/vidchain-agbar/vidchain-agbar-backend/k8s/configmap-pro.yml'  
  # Kubernetes namespace
  namespace: 'production'
  # Image tagging: application version - build
  tagAgbarBackend: '$(Build.BuildNumber)'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build stage'
  jobs:
  - job: GetShortCommit
    displayName: 'retrieve commit hash'
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        commit=$(Build.SourceVersion)
        shortCommit=${commit:0:7}
        echo "##vso[build.updatebuildnumber]$(Build.BuildId)-commit.$shortCommit"
      displayName: 'retrieve $(packageJson) version'
  - job: BuildAgbarBackend
    displayName: 'Build Agbar Backend'
    dependsOn: GetShortCommit
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Login ACR
      inputs:
        command: login
        containerRegistry: $(dockerRegistryServiceConnection)
    - script: "docker pull $(agbarBackendRepoEndpoint):latest"
      displayName: Pull latest for layer caching
      continueOnError: true # for first build, no cache
    - task: Docker@2
      displayName: "build --cache-from=$(agbarBackendRepoEndpoint):latest"
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(agbarBackendRepo)'
        command: 'build'
        Dockerfile: $(agbarBackendDocker)
        arguments: '--cache-from=$(agbarBackendRepoEndpoint):latest' 
        tags: |
          $(tagAgbarBackend)
          latest
    - task: Docker@2
      displayName: "push"
      inputs:
        command: push
        containerRegistry: "$(dockerRegistryServiceConnection)"
        repository: $(agbarBackendRepo) 
        tags: |
          $(tagAgbarBackend)
          latest        
- stage: Deploy
  displayName: 'Deploy stage'
  dependsOn: Build
  jobs:
  - deployment: DeployAgbarBackend
    displayName: 'Deploy Agbar Backend'
    pool:
      vmImage: $(vmImageName)
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: Kubernetes@1
            displayName: Create/update configmap
            inputs:
              connectionType: Azure Resource Manager
              azureSubscriptionEndpoint: $(azureSubscriptionEndpoint) 
              azureResourceGroup: $(azureResourceGroup)
              kubernetesCluster: $(kubernetesCluster)
              command: apply
              arguments: -f $(agbarBackendConfigMap) -n $(namespace)
          - task: KubernetesManifest@0
            displayName: Create/update deployment
            inputs:              
              kubernetesServiceConnection: $(kubernetesServiceConnection)
              namespace: $(namespace)
              manifests: $(agbarBackendKubernetes)
              containers: |
                $(agbarBackendRepoEndpoint):$(tagAgbarBackend)