trigger:
  branches:
    include:
      - staging
  paths:
    include:
      - implementations/vidchain-university/vidchain-university-backend

pr: none

resources:
- repo: self

variables:
  # Docker Buildkit improves image build performance
  DOCKER_BUILDKIT: 1
  # Image repository
  universityBackendRepo: 'university-backend'
  universityBackendRepoEndpoint: 'k8scrvidchaindev.azurecr.io/university-backend'
  # Dockerfiles
  universityBackendDocker: 'implementations/vidchain-university/vidchain-university-backend/Dockerfile'
  # Kubernetes YAML
  universityBackendKubernetes: 'implementations/vidchain-university/vidchain-university-backend/k8s/k8s-staging.yml'
  # Configmaps
  universityBackendConfigMap: 'implementations/vidchain-university/vidchain-university-backend/k8s/configmap-staging.yml'
  # Kubernetes namespace
  namespace: 'staging'
  # Image tagging: application version - build
  tagUniversityBackend: '$(Build.BuildNumber)'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  
stages:
- stage: Build
  displayName: 'Build stage'
  jobs:
  - job: GetShortCommit
    displayName: 'retrieve commit hash'
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        commit=$(Build.SourceVersion)
        shortCommit=${commit:0:7}
        echo "##vso[build.updatebuildnumber]$(Build.BuildId)-commit.$shortCommit"
      displayName: 'retrieve $(packageJson) version'
  - job: BuildUniversityBackend
    displayName: 'Build University Backend'
    dependsOn: GetShortCommit
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Login ACR
      inputs:
        command: login
        containerRegistry: $(dockerRegistryServiceConnection)
    - script: "docker pull $(universityBackendRepoEndpoint):latest"
      displayName: Pull latest for layer caching
      continueOnError: true # for first build, no cache
    - task: Docker@2
      displayName: "build --cache-from=$(universityBackendRepoEndpoint):latest"
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(universityBackendRepo)'
        command: 'build'
        Dockerfile: $(universityBackendDocker)
        arguments: '--cache-from=$(universityBackendRepoEndpoint):latest' 
        tags: |
          $(tagUniversityBackend)
          latest
    - task: Docker@2
      displayName: "push"
      inputs:
        command: push
        containerRegistry: "$(dockerRegistryServiceConnection)"
        repository: $(universityBackendRepo) 
        tags: |
          $(tagUniversityBackend)
          latest       
- stage: Deploy
  displayName: 'Deploy stage'
  dependsOn: Build
  jobs:
  - deployment: DeployUniversityBackend
    displayName: 'Deploy University Backend'
    pool:
      vmImage: $(vmImageName)
    environment: 'staging'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: Kubernetes@1
            displayName: Create/update configmap
            inputs:
              connectionType: Azure Resource Manager
              azureSubscriptionEndpoint: $(azureSubscriptionEndpoint) 
              azureResourceGroup: $(azureResourceGroup)
              kubernetesCluster: $(kubernetesCluster)
              command: apply
              arguments: -f $(universityBackendConfigMap) -n $(namespace)
          - task: KubernetesManifest@0
            displayName: Create/update deployment
            inputs:              
              kubernetesServiceConnection: $(kubernetesServiceConnection)
              namespace: $(namespace)
              manifests: $(universityBackendKubernetes)
              containers: |
                $(universityBackendRepoEndpoint):$(tagUniversityBackend)