trigger:
  branches:
    include:
      - staging
  paths:
    include:
      - implementations/vidchain-airline/vidchain-airline-frontend

pr: none

resources:
- repo: self

variables:
  # Docker Buildkit improves image build performance
  DOCKER_BUILDKIT: 1
  # Image repository
  airlineFrontendRepo: 'airline-frontend'
  airlineFrontendRepoEndpoint: 'k8scrvidchaindev.azurecr.io/airline-frontend'
  # Dockerfiles
  airlineFrontendDocker: 'implementations/vidchain-airline/vidchain-airline-frontend/Dockerfile'
  # Kubernetes YAML
  airlineFrontendKubernetes: 'implementations/vidchain-airline/vidchain-airline-frontend/k8s/k8s-staging.yml'
  # Kubernetes namespace
  namespace: 'staging'
  # Image tagging: application version - build
  tagAirlineFrontend: '$(Build.BuildNumber)'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build stage'
  jobs:
  - job: GetShortCommit
    displayName: 'retrieve commit hash'
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        commit=$(Build.SourceVersion)
        shortCommit=${commit:0:7}
        echo "##vso[build.updatebuildnumber]$(Build.BuildId)-commit.$shortCommit"
      displayName: 'retrieve $(packageJson) version'
  - job: BuildAirlineFrontend
    displayName: 'Build Airline Frontend'
    dependsOn: GetShortCommit
    pool:
      vmImage: $(vmImageName)
    steps:
    - bash: |
        cp ./implementations/vidchain-airline/vidchain-airline-frontend/envs/.env.staging ./implementations/vidchain-airline/vidchain-airline-frontend/.env
        echo -e "\nREACT_APP_API_KEY=$API_KEY" >> ./implementations/vidchain-airline/vidchain-airline-frontend/.env
      name: load_env_variables_file
      displayName: 'load env vars'
      env:
        API_KEY: $(API_KEY_AIRLINE)
    - task: Docker@2
      displayName: Login ACR
      inputs:
        command: login
        containerRegistry: $(dockerRegistryServiceConnection)
    - script: "docker pull $(airlineFrontendRepoEndpoint):latest"
      displayName: Pull latest for layer caching
      continueOnError: true # for first build, no cache
    - task: Docker@2
      displayName: "build --cache-from=$(airlineFrontendRepoEndpoint):latest"
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(airlineFrontendRepo)'
        command: 'build'
        Dockerfile: $(airlineFrontendDocker)
        arguments: '--cache-from=$(airlineFrontendRepoEndpoint):latest' 
        tags: |
          $(tagAirlineFrontend)
          latest
    - task: Docker@2
      displayName: "push"
      inputs:
        command: push
        containerRegistry: "$(dockerRegistryServiceConnection)"
        repository: $(airlineFrontendRepo) 
        tags: |
          $(tagAirlineFrontend)
          latest        
- stage: Deploy
  displayName: 'Deploy stage'
  dependsOn: Build
  jobs:
  - deployment: DeployAirlineFrontend
    displayName: 'Deploy Airline Frontend'
    pool:
      vmImage: $(vmImageName)
    environment: 'staging'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: KubernetesManifest@0
            displayName: Create/update deployment
            inputs:              
              kubernetesServiceConnection: $(kubernetesServiceConnection)
              namespace: $(namespace)
              manifests: $(airlineFrontendKubernetes)
              containers: |
                $(airlineFrontendRepoEndpoint):$(tagAirlineFrontend)