trigger:
  branches:
    include:
      - staging
  paths:
    include:
      - implementations/vidchain-airline/vidchain-airline-backend

pr: none

resources:
- repo: self

variables:
  # Docker Buildkit improves image build performance
  DOCKER_BUILDKIT: 1
  # Image repository
  airlineBackendRepo: 'airline-backend'
  airlineBackendRepoEndpoint: 'k8scrvidchaindev.azurecr.io/airline-backend'
  # Dockerfiles
  airlineBackendDocker: 'implementations/vidchain-airline/vidchain-airline-backend/Dockerfile'
  # Kubernetes YAML
  airlineBackendKubernetes: 'implementations/vidchain-airline/vidchain-airline-backend/k8s/k8s-staging.yml'
  # Configmaps
  airlineBackendConfigMap: 'implementations/vidchain-airline/vidchain-airline-backend/k8s/configmap-staging.yml'
  # Kubernetes namespace
  namespace: 'staging'
  # Image tagging: application version - build
  tagAirlineBackend: '$(Build.BuildNumber)'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  
stages:
- stage: Build
  displayName: 'Build stage'
  jobs:
  - job: GetShortCommit
    displayName: 'retrieve commit hash'
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        commit=$(Build.SourceVersion)
        shortCommit=${commit:0:7}
        echo "##vso[build.updatebuildnumber]$(Build.BuildId)-commit.$shortCommit"
      displayName: 'retrieve $(packageJson) version'
  - job: BuildAirlineBackend
    displayName: 'Build Airline Backend'
    dependsOn: GetShortCommit
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Login ACR
      inputs:
        command: login
        containerRegistry: $(dockerRegistryServiceConnection)
    - script: "docker pull $(airlineBackendRepoEndpoint):latest"
      displayName: Pull latest for layer caching
      continueOnError: true # for first build, no cache
    - task: Docker@2
      displayName: "build --cache-from=$(airlineBackendRepoEndpoint):latest"
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(airlineBackendRepo)'
        command: 'build'
        Dockerfile: $(airlineBackendDocker)
        arguments: '--cache-from=$(airlineBackendRepoEndpoint):latest' 
        tags: |
          $(tagAirlineBackend)
          latest
    - task: Docker@2
      displayName: "push"
      inputs:
        command: push
        containerRegistry: "$(dockerRegistryServiceConnection)"
        repository: $(airlineBackendRepo) 
        tags: |
          $(tagAirlineBackend)
          latest       
- stage: Deploy
  displayName: 'Deploy stage'
  dependsOn: Build
  jobs:
  - deployment: DeployAirlineBackend
    displayName: 'Deploy Airline Backend'
    pool:
      vmImage: $(vmImageName)
    environment: 'staging'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: Kubernetes@1
            displayName: Create/update configmap
            inputs:
              connectionType: Azure Resource Manager
              azureSubscriptionEndpoint: $(azureSubscriptionEndpoint) 
              azureResourceGroup: $(azureResourceGroup)
              kubernetesCluster: $(kubernetesCluster)
              command: apply
              arguments: -f $(airlineBackendConfigMap) -n $(namespace)
          - task: KubernetesManifest@0
            displayName: Create/update deployment
            inputs:              
              kubernetesServiceConnection: $(kubernetesServiceConnection)
              namespace: $(namespace)
              manifests: $(airlineBackendKubernetes)
              containers: |
                $(airlineBackendRepoEndpoint):$(tagAirlineBackend)