trigger:
  branches:
    include:
      - development
  paths:
    include:
      - implementations/vidchain-health-center/vidchain-health-center-frontend

pr: none

resources:
- repo: self

variables:
  # Docker Buildkit improves image build performance
  DOCKER_BUILDKIT: 1
  # Image repository
  healthCenterFrontendRepo: 'health-center-frontend'
  healthCenterFrontendRepoEndpoint: 'k8scrvidchaindev.azurecr.io/health-center-frontend'
  # Dockerfiles
  healthCenterFrontendDocker: 'implementations/vidchain-health-center/vidchain-health-center-frontend/Dockerfile'
  # Kubernetes YAML
  healthCenterFrontendKubernetes: 'implementations/vidchain-health-center/vidchain-health-center-frontend/k8s/k8s-dev.yml'
  # Kubernetes namespace
  namespace: 'development'
  # Image tagging: application version - build
  tagHealthCenterFrontend: '$(Build.BuildNumber)'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  
stages:
- stage: Build
  displayName: 'Build stage'
  jobs:
  - job: GetShortCommit
    displayName: 'retrieve commit hash'
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        commit=$(Build.SourceVersion)
        shortCommit=${commit:0:7}
        echo "##vso[build.updatebuildnumber]$(Build.BuildId)-commit.$shortCommit"
      displayName: 'retrieve $(packageJson) version'
  - job: BuildHealthCenterFrontend
    displayName: 'Build Health Center Frontend'
    dependsOn: GetShortCommit
    pool:
      vmImage: $(vmImageName)
    steps:
    - bash: |
        cp ./implementations/vidchain-health-center/vidchain-health-center-frontend/envs/.env.development ./implementations/vidchain-health-center/vidchain-health-center-frontend/.env
        echo -e "\nREACT_APP_API_KEY=$API_KEY" >> ./implementations/vidchain-health-center/vidchain-health-center-frontend/.env
      name: load_env_variables_file
      displayName: 'load env vars'
      env:
        API_KEY: $(API_KEY_HEALTH_CENTER)
    - task: Docker@2
      displayName: Login ACR
      inputs:
        command: login
        containerRegistry: $(dockerRegistryServiceConnection)
    - script: "docker pull $(healthCenterFrontendRepoEndpoint):latest"
      displayName: Pull latest for layer caching
      continueOnError: true # for first build, no cache
    - task: Docker@2
      displayName: "build --cache-from=$(healthCenterFrontendRepoEndpoint):latest"
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(healthCenterFrontendRepo)'
        command: 'build'
        Dockerfile: $(healthCenterFrontendDocker)
        arguments: '--cache-from=$(healthCenterFrontendRepoEndpoint):latest' 
        tags: |
          $(tagHealthCenterFrontend)
          latest
    - task: Docker@2
      displayName: "push"
      inputs:
        command: push
        containerRegistry: "$(dockerRegistryServiceConnection)"
        repository: $(healthCenterFrontendRepo) 
        tags: |
          $(tagHealthCenterFrontend)
          latest        
- stage: Deploy
  displayName: 'Deploy stage'
  dependsOn: Build
  jobs:
  - deployment: DeployHealthCenterFrontend
    displayName: 'Deploy Health Center Frontend'
    pool:
      vmImage: $(vmImageName)
    environment: 'development'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: KubernetesManifest@0
            displayName: Create/update deployment
            inputs:              
              kubernetesServiceConnection: $(kubernetesServiceConnection)
              namespace: $(namespace)
              manifests: $(healthCenterFrontendKubernetes)
              containers: |
                $(healthCenterFrontendRepoEndpoint):$(tagHealthCenterFrontend)